# Generated by Django 4.1.4 on 2024-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_playbookexecution_playbookexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookexecution',
            name='time_range',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playbookexecution',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'UNKNOWN_STATUS'), (1, 'CREATED'), (2, 'RUNNING'), (3, 'FINISHED'), (4, 'FAILED')], db_index=True, default=1, null=True),
        ),
    ]
