# Generated by Django 4.1.4 on 2024-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_playbookexecution_time_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playbookstep',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playbooktaskdefinition',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'METRIC'), (2, 'DECISION'), (3, 'DATA_FETCH'), (4, 'DOCUMENTATION'), (5, 'ACTION')], db_index=True),
        ),
    ]
