# Generated by Django 4.1.4 on 2024-05-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_playbook_description_playbookstep_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookstep',
            name='interpreter_type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN_I'), (1, 'BASIC_I'), (2, 'STATISTICAL_I'), (3, 'LLM_CHAT_GPT_VISION_I')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='playbooktaskdefinition',
            name='interpreter_type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN_I'), (1, 'BASIC_I'), (2, 'STATISTICAL_I'), (3, 'LLM_CHAT_GPT_VISION_I')], db_index=True, default=1),
        ),
    ]
