# Generated by Django 4.1.13 on 2024-05-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('executor', '0006_playbookexecutionlog_interpretation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBookStepTaskDefinitionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('playbook_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.playbookstep')),
                ('playbook_task_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.playbooktaskdefinition')),
            ],
            options={
                'unique_together': {('account', 'playbook_step', 'playbook_task_definition')},
            },
        ),
    ]
