# Generated by Django 4.1.13 on 2024-05-10 11:05

from django.db import migrations


def set_playbook_step_task_definition_mapping(apps, schema_editor):
    PlayBookTaskDefinition = apps.get_model("executor", "PlayBookTaskDefinition")
    PlayBookStepTaskDefinitionMapping = apps.get_model("executor", "PlayBookStepTaskDefinitionMapping")

    for task in PlayBookTaskDefinition.objects.all():
        playbook_step = task.playbook_step
        PlayBookStepTaskDefinitionMapping.objects.get_or_create(
            account=task.account,
            playbook_step=playbook_step,
            playbook_task_definition=task
        )


class Migration(migrations.Migration):
    dependencies = [
        ('executor', '0007_playbooksteptaskdefinitionmapping'),
    ]

    operations = [
        migrations.RunPython(set_playbook_step_task_definition_mapping, migrations.RunPython.noop)
    ]
