# Generated by Django 4.1.13 on 2024-05-10 11:57

from django.db import migrations


def remove_duplicate_tasks(apps, schema_editor):
    PlayBookTaskDefinition = apps.get_model("executor", "PlayBookTaskDefinition")
    PlayBookStepTaskDefinitionMapping = apps.get_model("executor", "PlayBookStepTaskDefinitionMapping")

    all_tasks = PlayBookTaskDefinition.objects.all()
    for idx, task in enumerate(all_tasks):
        for other_task in all_tasks[idx + 1:]:
            if task.account == other_task.account and task.name == other_task.name and task.task_md5 == other_task.task_md5:
                playbook_step_task_mapping = PlayBookStepTaskDefinitionMapping.objects.filter(
                    playbook_task_definition=other_task
                )
                for mapping in playbook_step_task_mapping:
                    mapping.playbook_task_definition = task
                    mapping.save()
                other_task.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('executor', '0008_populate_step_task_mapping'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_tasks, migrations.RunPython.noop)
    ]
