# Generated by Django 4.1.13 on 2024-05-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('executor', '0009_remove_duplicate_tasks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbooktaskdefinition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playbookstep',
            name='tasks',
            field=models.ManyToManyField(related_name='step_tasks', through='executor.PlayBookStepTaskDefinitionMapping', to='executor.playbooktaskdefinition'),
        ),
        migrations.AddField(
            model_name='playbooksteptaskdefinitionmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='playbooksteptaskdefinitionmapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playbooktaskdefinition',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='playbooktaskdefinition',
            unique_together={('account', 'name', 'task_md5', 'created_by')},
        ),
        migrations.RemoveField(
            model_name='playbooktaskdefinition',
            name='interpreter_type',
        ),
        migrations.RemoveField(
            model_name='playbooktaskdefinition',
            name='playbook_step',
        ),
    ]
