# Generated by Django 4.1.13 on 2024-05-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('executor', '0010_alter_playbooktaskdefinition_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbooktaskdefinition',
            name='playbook',
        ),
        migrations.AddField(
            model_name='playbookstep',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayBookStepMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.playbook')),
                ('playbook_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.playbookstep')),
            ],
            options={
                'unique_together': {('account', 'playbook', 'playbook_step')},
            },
        ),
    ]
