# Generated by Django 4.1.13 on 2024-05-10 12:15

from django.db import migrations


def set_playbook_step_mapping(apps, schema_editor):
    PlayBookStep = apps.get_model("executor", "PlayBookStep")
    PlayBookStepMapping = apps.get_model("executor", "PlayBookStepMapping")

    for step in PlayBookStep.objects.all():
        playbook = step.playbook
        PlayBookStepMapping.objects.get_or_create(
            account=step.account,
            playbook_step=step,
            playbook=playbook
        )


class Migration(migrations.Migration):
    dependencies = [
        ('executor', '0011_remove_playbooktaskdefinition_playbook_and_more'),
    ]

    operations = [
        migrations.RunPython(set_playbook_step_mapping, migrations.RunPython.noop)
    ]
