# Generated by Django 4.1.13 on 2024-05-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('executor', '0013_remove_playbookstep_playbook_playbook_steps'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbook',
            unique_together={('account', 'name', 'created_by')},
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='is_generated',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='playbook',
        ),
    ]
