# Generated by Django 4.1.13 on 2024-05-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0014_alter_playbook_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbookstepmapping',
            unique_together=set(),
        ),
    ]
