# Generated by Django 4.1.13 on 2024-05-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0015_alter_playbookstepmapping_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbookstep',
            name='is_active',
        ),
    ]
