# Generated by Django 4.1.13 on 2024-05-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0016_remove_playbookstep_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbooksteptaskdefinitionmapping',
            name='is_active',
        ),
    ]
