# Generated by Django 4.1.13 on 2024-05-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0017_remove_playbooksteptaskdefinitionmapping_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbooksteptaskdefinitionmapping',
            unique_together=set(),
        ),
    ]
