# Generated by Django 4.1.13 on 2024-05-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0020_rebuild_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbooktaskdefinition',
            name='type',
        ),
    ]
