# Generated by Django 4.1.13 on 2024-05-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('executor', '0022_rename_playbookexecutionlog_playbooktaskexecutionlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayBookTaskDefinition',
            new_name='PlayBookTask',
        ),
    ]
