# Generated by Django 4.1.13 on 2024-05-17 11:34
from hashlib import md5

from django.db import migrations

from executor.utils.old_to_new_model_transformers import transform_old_task_definition_to_new


def transform_playbook_task(apps, schema_editor):
    PlayBookTask = apps.get_model("executor", "PlayBookTask")

    for db_task in PlayBookTask.objects.all():
        try:
            task = db_task.task
            new_task_def = transform_old_task_definition_to_new(task)
            task_md5 = md5(str(new_task_def).encode('utf-8')).hexdigest()

            db_task.task = new_task_def
            db_task.task_md5 = task_md5
            db_task.save()
        except Exception as e:
            print('skip task transformation for task id: ', db_task.id)
            print(f"Error transforming task {db_task.id}: {e}")


class Migration(migrations.Migration):
    dependencies = [
        ('executor', '0024_migrate_playbook_executions_to_new_proto'),
    ]

    operations = [
        migrations.RunPython(transform_playbook_task, migrations.RunPython.noop)
    ]
