# Generated by Django 4.1.13 on 2024-05-21 05:48

from django.db import migrations

from protos.playbooks.playbook_pb2 import PlaybookTask as PlaybookTaskProto
from utils.proto_utils import dict_to_proto


def populate_task_connector_mapping(apps, schema_editor):
    PlayBook = apps.get_model("executor", "PlayBook")
    PlayBookStepMapping = apps.get_model("executor", "PlayBookStepMapping")
    PlayBookTask = apps.get_model("executor", "PlayBookTask")
    PlayBookStepTaskDefinitionMapping = apps.get_model("executor", "PlayBookStepTaskDefinitionMapping")
    Connector = apps.get_model("connectors", "Connector")
    PlayBookStepTaskConnectorMapping = apps.get_model("executor", "PlayBookStepTaskConnectorMapping")

    for playbook in PlayBook.objects.all():
        playbook_steps = PlayBookStepMapping.objects.filter(playbook=playbook, is_active=True).values_list(
            'playbook_step', flat=True)
        for step in playbook_steps:
            for task in PlayBookStepTaskDefinitionMapping.objects.filter(playbook_step_id=step).values_list(
                    'playbook_task_definition', flat=True):
                db_task = PlayBookTask.objects.get(id=task)
                playbook_task: PlaybookTaskProto = dict_to_proto(db_task.task, PlaybookTaskProto)
                source = playbook_task.source
                connector = Connector.objects.filter(connector_type=source, is_active=True).values_list('id', flat=True)
                if connector:
                    PlayBookStepTaskConnectorMapping.objects.create(
                        account_id=db_task.account.id,
                        playbook_id=playbook.id,
                        playbook_step_id=step,
                        playbook_task_id=task,
                        connector_id=connector[0],
                        is_active=True
                    )


class Migration(migrations.Migration):
    dependencies = [
        ('executor', '0027_playbooksteptaskconnectormapping_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_task_connector_mapping, migrations.RunPython.noop)
    ]
