# Generated by Django 4.1.13 on 2024-05-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0012_alter_connectormetadatamodelstore_model_type'),
        ('accounts', '0002_userinvitation'),
        ('executor', '0027_migrate_api_call_task_to_new_def'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBookStepTaskConnectorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectors.connector')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.playbook')),
                ('playbook_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.playbookstep')),
                ('playbook_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.playbooktask')),
            ],
        ),
        migrations.AddField(
            model_name='playbooktask',
            name='task_connector_source',
            field=models.ManyToManyField(related_name='task_source', through='executor.PlayBookStepTaskConnectorMapping', to='connectors.connector'),
        ),
    ]
