# Generated by Django 4.1.13 on 2024-05-28 09:40
from hashlib import md5

from django.db import migrations


def transform_playbook_eks_task(apps, schema_editor):
    PlayBookTask = apps.get_model("executor", "PlayBookTask")

    for db_task in PlayBookTask.objects.all():
        try:
            task = db_task.task
            task_source = task.get('source', '')
            if task_source.lower() != 'eks':
                continue
            eks_task = task.get('eks')
            eks_task_type = eks_task.get('type', '')
            task_type_lower = eks_task_type.lower()
            command = eks_task.pop('command', {})

            new_task_def = {
                'eks': {
                    'type': eks_task_type,
                    task_type_lower: command,
                },
                'source': 'EKS'
            }
            task_md5 = md5(str(new_task_def).encode('utf-8')).hexdigest()
            db_task.task = new_task_def
            db_task.task_md5 = task_md5
            db_task.save()
        except Exception as e:
            print('skip task transformation for task id: ', db_task.id)
            print(f"Error transforming task {db_task.id}: {e}")
            continue


class Migration(migrations.Migration):
    dependencies = [
        ('executor', '0028_map_connectors_to_task'),
    ]

    operations = [
        migrations.RunPython(transform_playbook_eks_task, migrations.RunPython.noop)
    ]
