# Generated by Django 4.1.13 on 2024-05-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('connectors', '0012_alter_connectormetadatamodelstore_model_type'),
        ('executor', '0030_migrate_eks_task_to_new_def'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbooksteptaskconnectormapping',
            unique_together={('account', 'playbook', 'playbook_step', 'playbook_task', 'connector')},
        ),
    ]
