# Generated by Django 4.1.13 on 2024-06-05 15:59

from django.db import migrations
from hashlib import md5


def transform_playbook_iframe_task(apps, schema_editor):
    PlayBookTask = apps.get_model("executor", "PlayBookTask")

    for db_task in PlayBookTask.objects.all():
        try:
            task = db_task.task
            task_source = task.get('source', '')
            if task_source.lower() != 'documentation' or 'iframe' not in task:
                continue
            iframe_url = task.get('iframe', {}).get('iframe_url', '')
            new_task_def = {
                'documentation': {
                    'type': 'IFRAME',
                    'iframe': {
                        'iframe_url': iframe_url
                    },
                },
                'source': 'DOCUMENTATION'
            }
            task_md5 = md5(str(new_task_def).encode('utf-8')).hexdigest()
            db_task.task = new_task_def
            db_task.task_md5 = task_md5
            db_task.save()
        except Exception as e:
            print('skip task transformation for task id: ', db_task.id)
            print(f"Error transforming task {db_task.id}: {e}")
            continue


class Migration(migrations.Migration):
    dependencies = [
        ('executor', '0031_alter_playbooksteptaskconnectormapping_unique_together'),
    ]

    operations = [
        migrations.RunPython(transform_playbook_iframe_task, migrations.RunPython.noop)
    ]
