# Generated by Django 4.1.13 on 2024-06-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0031_alter_playbooksteptaskconnectormapping_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookstepexecutionlog',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbookstepexecutionlog',
            name='time_range',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbooktaskexecutionlog',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbooktaskexecutionlog',
            name='time_range',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
