# Generated by Django 4.1.13 on 2024-06-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0035_playbooksteprelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookstep',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
