# Generated by Django 4.1.13 on 2024-06-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0037_playbooksteprelationexecutionlog_evaluation_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbookstep',
            name='reference_id',
        ),
    ]
