# Generated by Django 4.1.13 on 2024-06-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('executor', '0038_remove_playbookstep_reference_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playbooksteprelation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playbooksteprelation',
            name='condition_md5',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='playbooksteprelation',
            unique_together={('account', 'playbook', 'parent', 'child', 'condition_md5')},
        ),
    ]
