# Generated by Django 4.1.13 on 2024-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("executor", "0039_alter_playbooksteprelation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbooksteprelationexecutionlog",
            name="interpretation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
