# Generated by Django 4.1.13 on 2024-07-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0041_migrate_logs_task_executions_to_new_def'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbooktaskexecutionlog',
            name='execution_global_variable_set',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
