# Generated by Django 4.1.13 on 2024-07-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0043_migrate_logs_task_executions_to_new_def'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbooktask',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
