# Generated by Django 4.1.13 on 2024-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0043_migrate_logs_task_executions_to_new_def'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbooksteptaskdefinitionmapping',
            name='playbook_task_execution_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
