# Generated by Django 4.1.13 on 2024-08-05 07:25
from hashlib import md5

from django.db import migrations


def transform_step_relation_condition(apps, schema_editor):
    PlayBookStepRelation = apps.get_model("executor", "PlayBookStepRelation")

    for step_relation in PlayBookStepRelation.objects.all():
        try:
            condition = step_relation.condition
            if not condition:
                continue
            updated_condition = {
                "rule_sets": [
                    condition
                ],
                "logical_operator": "AND_LO"
            }
            update_condition_md5 = md5(str(updated_condition).encode('utf-8')).hexdigest()
            step_relation.condition = updated_condition
            step_relation.condition_md5 = update_condition_md5
            step_relation.save()
        except Exception as e:
            print('skip task transformation for task id: ', step_relation.id)
            print(f"Error transforming task {step_relation.id}: {e}")
            continue


class Migration(migrations.Migration):
    dependencies = [
        ('executor', '0044_playbooksteptaskdefinitionmapping_playbook_task_execution_config'),
    ]

    operations = [
        migrations.RunPython(transform_step_relation_condition, migrations.RunPython.noop)
    ]
