# Generated by Django 4.1.13 on 2025-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executor", "0046_secret_secret_executor_se_key_60cc82_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="secret",
            name="unique_active_key_per_account",
        ),
        migrations.AddIndex(
            model_name="secret",
            index=models.Index(
                fields=["account", "created_by"], name="executor_se_account_02f4c3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("key", "account"), name="unique_key_per_account"
            ),
        ),
    ]
