export enum ExecutionStatus {
  CREATED = "CREATED",
  RUNNING = "RUNNING",
  FINISHED = "FINISHED",
  FAILED = "FAILED",
  WORKFLOW_CREATED = "WORKFLOW_CREATED",
  WORKFLOW_RUNNING = "WORKFLOW_RUNNING",
}
