# Generated by Django 4.1.4 on 2024-04-16 11:36

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(db_index=True)),
                ('fargs', models.JSONField(blank=True, null=True)),
                ('md5_fargs', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('max_retries', models.IntegerField(default=0)),
                ('retry_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
            options={
                'unique_together': {('task', 'md5_fargs')},
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_uuid', models.CharField(db_index=True, max_length=256)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'SKIPPED'), (2, 'SCHEDULED'), (3, 'RUNNING'), (4, 'COMPLETED'), (5, 'FAILED')], db_index=True, default=management.models.PeriodicTaskStatus['UNKNOWN'], null=True)),
                ('result', models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'SUCCESS'), (2, 'FAILURE')], db_index=True, default=management.models.PeriodicTaskResult['UNKNOWN'], null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.task')),
            ],
            options={
                'unique_together': {('task', 'task_uuid')},
            },
        ),
    ]
