apiVersion: v1
kind: Service
metadata:
  name: server
  annotations:
    meta.helm.sh/release-name: {{ .Release.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: server
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080