version: "3.9"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  setup_db:
    image: public.ecr.aws/y9s1f3r5/drdroid/playbooks-backend:latest
    platform: linux/amd64
    command: ./setup_db.sh
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  server:
    image: public.ecr.aws/y9s1f3r5/drdroid/playbooks-backend:latest
    platform: linux/amd64
    command: ./start-server.sh
    ports:
      - 8080:8080
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
    depends_on:
      - db
      - redis
      - setup_db
    networks:
      - mynetwork

  celery_worker:
    image: public.ecr.aws/y9s1f3r5/drdroid/playbooks-backend:latest
    platform: linux/amd64
    command: ./start-celery-worker.sh
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    depends_on:
      - db
      - redis
      - setup_db
    networks:
      - mynetwork

  workflow_scheduler_celery_worker:
    image: public.ecr.aws/y9s1f3r5/drdroid/playbooks-backend:latest
    platform: linux/amd64
    command: ./start-celery-worker.sh
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - "CELERY_QUEUE=workflow_scheduler"
    depends_on:
      - db
      - redis
      - setup_db
    networks:
      - mynetwork

  workflow_executor_celery_worker:
    image: public.ecr.aws/y9s1f3r5/drdroid/playbooks-backend:latest
    platform: linux/amd64
    command: ./start-celery-worker.sh
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - "CELERY_QUEUE=workflow_executor"
    depends_on:
      - db
      - redis
      - setup_db
    networks:
      - mynetwork

  workflow_action_execution_celery_worker:
    image: public.ecr.aws/y9s1f3r5/drdroid/playbooks-backend:latest
    platform: linux/amd64
    command: ./start-celery-worker.sh
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - "CELERY_QUEUE=workflow_action_execution"
    depends_on:
      - db
      - redis
      - setup_db
    networks:
      - mynetwork

  celery_beat:
    image: public.ecr.aws/y9s1f3r5/drdroid/playbooks-backend:latest
    platform: linux/amd64
    command: ./start-celery-beat.sh
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    depends_on:
      - db
      - redis
      - setup_db
    networks:
      - mynetwork

  web:
    image: public.ecr.aws/y9s1f3r5/drdroid/playbooks-web:latest
    platform: linux/amd64
    environment:
      - VITE_REACT_APP_POSTHOG_ENABLED=true
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
