"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SSOProvider:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SSOProviderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SSOProvider.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _SSOProvider.ValueType  # 0
    OKTA: _SSOProvider.ValueType  # 1

class SSOProvider(_SSOProvider, metaclass=_SSOProviderEnumTypeWrapper): ...

UNKNOWN: SSOProvider.ValueType  # 0
OKTA: SSOProvider.ValueType  # 1
global___SSOProvider = SSOProvider

@typing_extensions.final
class AccountApiToken(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    key: builtins.str
    created_by: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    account_id: builtins.int
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        created_by: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        account_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "created_at", b"created_at", "created_by", b"created_by", "key", b"key"]) -> None: ...

global___AccountApiToken = AccountApiToken

@typing_extensions.final
class UserFlags(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_EMAIL_VERIFIED_FIELD_NUMBER: builtins.int
    IS_ACCOUNT_OWNER_FIELD_NUMBER: builtins.int
    @property
    def is_email_verified(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def is_account_owner(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        is_email_verified: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        is_account_owner: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["is_account_owner", b"is_account_owner", "is_email_verified", b"is_email_verified"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_account_owner", b"is_account_owner", "is_email_verified", b"is_email_verified"]) -> None: ...

global___UserFlags = UserFlags

@typing_extensions.final
class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    USER_FLAGS_FIELD_NUMBER: builtins.int
    id: builtins.int
    email: builtins.str
    first_name: builtins.str
    last_name: builtins.str
    @property
    def user_flags(self) -> global___UserFlags: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        email: builtins.str = ...,
        first_name: builtins.str = ...,
        last_name: builtins.str = ...,
        user_flags: global___UserFlags | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user_flags", b"user_flags"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["email", b"email", "first_name", b"first_name", "id", b"id", "last_name", b"last_name", "user_flags", b"user_flags"]) -> None: ...

global___User = User
