apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'fluentd'
  annotations:
    meta.helm.sh/release-name: {{ .Release.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.12-debian-1
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
            - name: posfile
              mountPath: /var/log/fluentd
            - name: varlog
              mountPath: /var/log/containers
          command: ["fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins"]
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log/containers
        - name: posfile
          emptyDir: {}
