apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd/containers.pos
      tag kube.*
      <parse>
        @type none
      </parse>
    </source>

    <match **>
      @type forward
      <server>
        host central-log-server
        port 24224
      </server>
    </match>