apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/celery-beat-*
      pos_file /var/log/fluentd/celery-beat.pos
      tag celery-beat
      <parse>
        @type none 
      </parse>
    </source>

    <match **>
      @type stdout
    </match>