apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluentd-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: fluentd-sa
  namespace: default
roleRef:
  kind: Role
  name: fluentd-role
  apiGroup: rbac.authorization.k8s.io