# Generated by Django 4.1.4 on 2024-04-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userinvitation"),
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackConnectorAlertTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_tag",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlackConnectorAlertType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connectors.connectorkey",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connectors.connector",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "connector", "channel", "alert_type")},
            },
        ),
        migrations.CreateModel(
            name="SlackConnectorDataReceived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "alert_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("tags", models.JSONField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "data_timestamp",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connectors.connector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlackConnectorDataReceivedAlertTagMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "data_timestamp",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "alert_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connectors.slackconnectoralerttag",
                    ),
                ),
                (
                    "slack_connector_data_received",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connectors.slackconnectordatareceived",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("account", "slack_connector_data_received", "alert_tag")
                },
            },
        ),
        migrations.AddField(
            model_name="slackconnectordatareceived",
            name="db_alert_tags",
            field=models.ManyToManyField(
                related_name="tags",
                through="connectors.SlackConnectorDataReceivedAlertTagMapping",
                to="connectors.slackconnectoralerttag",
            ),
        ),
        migrations.AddField(
            model_name="slackconnectordatareceived",
            name="db_alert_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="connectors.slackconnectoralerttype",
            ),
        ),
        migrations.AddField(
            model_name="slackconnectordatareceived",
            name="slack_channel_metadata_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="connectors.connectormetadatamodelstore",
            ),
        ),
        migrations.AddField(
            model_name="slackconnectoralerttag",
            name="alert_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="connectors.slackconnectoralerttype",
            ),
        ),
        migrations.AddField(
            model_name="slackconnectoralerttag",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="connectors.connectorkey",
            ),
        ),
        migrations.AddField(
            model_name="slackconnectoralerttag",
            name="connector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="connectors.connector"
            ),
        ),
        migrations.CreateModel(
            name="ConnectorPeriodicRunMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField()),
                ("task_run_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "UNKNOWN"),
                            (1, "STARTED"),
                            (2, "FINISHED"),
                            (3, "ERROR"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="connectors.connector",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="slackconnectoralerttag",
            unique_together={
                ("account", "connector", "channel", "alert_type", "alert_tag")
            },
        ),
    ]
