# Generated by Django 4.1.4 on 2024-04-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0002_alter_connectormetadatamodelstore_model_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("protocol", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
