# Generated by Django 4.1.13 on 2024-05-14 06:04

from django.db import migrations


def name_all_active_connectors(apps, schema_editor):
    PlayBookTaskDefinition = apps.get_model("executor", "PlayBookTaskDefinition")
    PlayBookStepTaskDefinitionMapping = apps.get_model("executor", "PlayBookStepTaskDefinitionMapping")

    all_tasks = PlayBookTaskDefinition.objects.all()
    for idx, task in enumerate(all_tasks):
        for other_task in all_tasks[idx + 1:]:
            if task.account == other_task.account and task.name == other_task.name and task.task_md5 == other_task.task_md5:
                playbook_step_task_mapping = PlayBookStepTaskDefinitionMapping.objects.filter(
                    playbook_task_definition=other_task
                )
                for mapping in playbook_step_task_mapping:
                    mapping.playbook_task_definition = task
                    mapping.save()
                other_task.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('connectors', '0008_alter_connectorkey_key_type_and_more'),
    ]

    operations = [
    ]
