# Generated by Django 4.1.13 on 2024-06-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0015_pagerdutyconnectordatareceived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagerdutyconnectordatareceived',
            name='text',
        ),
    ]
