# Generated by Django 4.1.13 on 2024-06-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0015_pagerdutyconnectordatareceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerdutyconnectordatareceived',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
