# Generated by Django 4.1.13 on 2024-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0016_remove_pagerdutyconnectordatareceived_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerdutyconnectordatareceived',
            name='alert_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagerdutyconnectordatareceived',
            name='alert_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
