# Generated by Django 4.1.13 on 2024-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountuseroauth2sessioncodestore'),
        ('connectors', '0021_alter_connectorkey_key_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectorkey',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='connectorkey',
            name='key_md5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='connectorkey',
            unique_together={('account', 'connector', 'key_type', 'key_md5')},
        ),
    ]
