# Generated by Django 4.1.13 on 2024-07-25 08:58

from django.db import migrations


def migrate_bash_sources(apps, schema_editor):
    Connector = apps.get_model("connectors", "Connector")

    for c in Connector.objects.filter(connector_type=39):
        try:
            c.connector_type = 41
            c.save()
        except Exception as e:
            print(f"Failed to migrate source for connector {c.id} with error: {str(e)}")

    ConnectorMetadataModelStore = apps.get_model("connectors", "ConnectorMetadataModelStore")

    for cm in ConnectorMetadataModelStore.objects.filter(connector_type=39):
        try:
            cm.connector_type = 41
            cm.save()
        except Exception as e:
            print(f"Failed to migrate source for connector metadata model {cm.id} with error: {str(e)}")


class Migration(migrations.Migration):
    dependencies = [
        ('connectors', '0027_alter_connectormetadatamodelstore_model_type'),
    ]

    operations = [
        migrations.RunPython(migrate_bash_sources, migrations.RunPython.noop)
    ]
