# Generated by Django 4.1.13 on 2024-10-02 09:40

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0031_alter_connector_connector_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorkey',
            name='key',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='connectorkey',
            name='key_md5',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
