# Generated by Django 4.1.13 on 2024-10-02 09:41

from django.db import migrations


def encrypt_existing_data(apps, schema_editor):
    ConnectorKey = apps.get_model('connectors', 'ConnectorKey')
    for obj in ConnectorKey.objects.all():
        obj.key = obj.key  # triggers encryption during save
        obj.key_md5 = obj.key_md5  # triggers encryption during save
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('connectors', '0032_alter_connectorkey_key_alter_connectorkey_key_md5'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_data),
    ]
