djangoDatabaseHost: postgresql-service
djangoDatabasePort: 5432
djangoDatabaseName: db
djangoDatabaseUsername: user
djangoDatabasePassword: pass

redisUrl: "redis://redis-service:6379/0"
emailPasswordAuthEnabled: False

service:
  type: ClusterIP
  port: 8080

debug: "no"