apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  annotations:
    meta.helm.sh/release-name: {{ .Release.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379