apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-server'
  labels:
    katenary.io/component: server
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: server
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
