apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-web'
  labels:
    katenary.io/component: web
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: web
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: web
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-server
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking server port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-server 8080 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: web
          image: '{{ .Values.web.repository.image }}{{ if ne .Values.web.repository.tag "" }}:{{ .Values.web.repository.tag }}{{ end }}'
          ports:
            - name: web
              containerPort: 80
          env:
            - name: REACT_APP_POSTHOG_ENABLED
              value: '{{ tpl .Values.web.environment.REACT_APP_POSTHOG_ENABLED . }}'

