# Generated by Django 4.1.13 on 2024-07-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUserOauth2SessionCodeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(db_index=True)),
                ('code_verifier', models.TextField(db_index=True)),
                ('code_challenge', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField(db_index=True)),
            ],
            options={
                'unique_together': {('session_id', 'code_verifier', 'code_challenge')},
            },
        ),
    ]
