"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.base_pb2
import protos.playbooks.playbook_pb2
import protos.playbooks.workflow_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RunPlaybookTaskRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PLAYBOOK_TASK_DEFINITION_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def playbook_task_definition(self) -> protos.playbooks.playbook_pb2.PlaybookTaskDefinition: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        playbook_task_definition: protos.playbooks.playbook_pb2.PlaybookTaskDefinition | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_task_definition", b"playbook_task_definition"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_task_definition", b"playbook_task_definition"]) -> None: ...

global___RunPlaybookTaskRequest = RunPlaybookTaskRequest

@typing_extensions.final
class RunPlaybookTaskResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    TASK_EXECUTION_RESULT_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    @property
    def task_execution_result(self) -> protos.playbooks.playbook_pb2.PlaybookTaskExecutionResult: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
        task_execution_result: protos.playbooks.playbook_pb2.PlaybookTaskExecutionResult | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "success", b"success", "task_execution_result", b"task_execution_result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "success", b"success", "task_execution_result", b"task_execution_result"]) -> None: ...

global___RunPlaybookTaskResponse = RunPlaybookTaskResponse

@typing_extensions.final
class RunPlaybookStepRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PLAYBOOK_STEP_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def playbook_step(self) -> protos.playbooks.playbook_pb2.PlaybookStepDefinition: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        playbook_step: protos.playbooks.playbook_pb2.PlaybookStepDefinition | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_step", b"playbook_step"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_step", b"playbook_step"]) -> None: ...

global___RunPlaybookStepRequest = RunPlaybookStepRequest

@typing_extensions.final
class RunPlaybookStepResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TASK_EXECUTION_RESULTS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def task_execution_results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.playbooks.playbook_pb2.PlaybookTaskExecutionResult]: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        task_execution_results: collections.abc.Iterable[protos.playbooks.playbook_pb2.PlaybookTaskExecutionResult] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["description", b"description", "message", b"message", "meta", b"meta", "name", b"name", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "message", b"message", "meta", b"meta", "name", b"name", "success", b"success", "task_execution_results", b"task_execution_results"]) -> None: ...

global___RunPlaybookStepResponse = RunPlaybookStepResponse

@typing_extensions.final
class GetPlaybooksRequest(google.protobuf.message.Message):
    """/////////////////// PlayBooks CRUD APIs /////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PLAYBOOK_IDS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def playbook_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        playbook_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_ids", b"playbook_ids"]) -> None: ...

global___GetPlaybooksRequest = GetPlaybooksRequest

@typing_extensions.final
class GetPlaybooksResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PLAYBOOKS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def playbooks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.playbooks.playbook_pb2.Playbook]: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        playbooks: collections.abc.Iterable[protos.playbooks.playbook_pb2.Playbook] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbooks", b"playbooks"]) -> None: ...

global___GetPlaybooksResponse = GetPlaybooksResponse

@typing_extensions.final
class CreatePlaybookRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PLAYBOOK_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def playbook(self) -> protos.playbooks.playbook_pb2.Playbook: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        playbook: protos.playbooks.playbook_pb2.Playbook | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["playbook", b"playbook"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "playbook", b"playbook"]) -> None: ...

global___CreatePlaybookRequest = CreatePlaybookRequest

@typing_extensions.final
class CreatePlaybookResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    PLAYBOOK_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    @property
    def playbook(self) -> protos.playbooks.playbook_pb2.Playbook: ...
    def __init__(
        self,
        *,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
        playbook: protos.playbooks.playbook_pb2.Playbook | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message", "playbook", b"playbook", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "playbook", b"playbook", "success", b"success"]) -> None: ...

global___CreatePlaybookResponse = CreatePlaybookResponse

@typing_extensions.final
class UpdatePlaybookRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYBOOK_ID_FIELD_NUMBER: builtins.int
    UPDATE_PLAYBOOK_OPS_FIELD_NUMBER: builtins.int
    @property
    def playbook_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def update_playbook_ops(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.playbooks.playbook_pb2.UpdatePlaybookOp]: ...
    def __init__(
        self,
        *,
        playbook_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        update_playbook_ops: collections.abc.Iterable[protos.playbooks.playbook_pb2.UpdatePlaybookOp] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["playbook_id", b"playbook_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["playbook_id", b"playbook_id", "update_playbook_ops", b"update_playbook_ops"]) -> None: ...

global___UpdatePlaybookRequest = UpdatePlaybookRequest

@typing_extensions.final
class UpdatePlaybookResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    def __init__(
        self,
        *,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success"]) -> None: ...

global___UpdatePlaybookResponse = UpdatePlaybookResponse

@typing_extensions.final
class ExecutePlaybookRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PLAYBOOK_ID_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def playbook_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        playbook_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_id", b"playbook_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_id", b"playbook_id"]) -> None: ...

global___ExecutePlaybookRequest = ExecutePlaybookRequest

@typing_extensions.final
class ExecutePlaybookResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    PLAYBOOK_RUN_ID_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    @property
    def playbook_run_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
        playbook_run_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "playbook_run_id", b"playbook_run_id", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "playbook_run_id", b"playbook_run_id", "success", b"success"]) -> None: ...

global___ExecutePlaybookResponse = ExecutePlaybookResponse

@typing_extensions.final
class ExecutionPlaybookGetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PLAYBOOK_RUN_ID_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def playbook_run_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        playbook_run_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_run_id", b"playbook_run_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_run_id", b"playbook_run_id"]) -> None: ...

global___ExecutionPlaybookGetRequest = ExecutionPlaybookGetRequest

@typing_extensions.final
class ExecutionPlaybookGetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    PLAYBOOK_EXECUTION_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    @property
    def playbook_execution(self) -> protos.playbooks.playbook_pb2.PlaybookExecution: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
        playbook_execution: protos.playbooks.playbook_pb2.PlaybookExecution | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "playbook_execution", b"playbook_execution", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "playbook_execution", b"playbook_execution", "success", b"success"]) -> None: ...

global___ExecutionPlaybookGetResponse = ExecutionPlaybookGetResponse

@typing_extensions.final
class ExecutionPlaybookAPIGetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    PLAYBOOK_EXECUTIONS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    @property
    def playbook_executions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.playbooks.playbook_pb2.PlaybookExecution]: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
        playbook_executions: collections.abc.Iterable[protos.playbooks.playbook_pb2.PlaybookExecution] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "playbook_executions", b"playbook_executions", "success", b"success"]) -> None: ...

global___ExecutionPlaybookAPIGetResponse = ExecutionPlaybookAPIGetResponse

@typing_extensions.final
class ExecutionsPlaybooksListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    PLAYBOOK_IDS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def playbook_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        playbook_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "playbook_ids", b"playbook_ids"]) -> None: ...

global___ExecutionsPlaybooksListRequest = ExecutionsPlaybooksListRequest

@typing_extensions.final
class ExecutionsPlaybooksListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    PLAYBOOK_EXECUTIONS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    @property
    def playbook_executions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.playbooks.playbook_pb2.PlaybookExecution]: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
        playbook_executions: collections.abc.Iterable[protos.playbooks.playbook_pb2.PlaybookExecution] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "meta", b"meta", "playbook_executions", b"playbook_executions", "success", b"success"]) -> None: ...

global___ExecutionsPlaybooksListResponse = ExecutionsPlaybooksListResponse

@typing_extensions.final
class GetWorkflowsRequest(google.protobuf.message.Message):
    """/////////////////// Workflows APIs /////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    WORKFLOW_IDS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def workflow_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        workflow_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "workflow_ids", b"workflow_ids"]) -> None: ...

global___GetWorkflowsRequest = GetWorkflowsRequest

@typing_extensions.final
class GetWorkflowsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    WORKFLOWS_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> protos.base_pb2.Meta: ...
    @property
    def workflows(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.playbooks.workflow_pb2.Workflow]: ...
    def __init__(
        self,
        *,
        meta: protos.base_pb2.Meta | None = ...,
        workflows: collections.abc.Iterable[protos.playbooks.workflow_pb2.Workflow] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta", b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["meta", b"meta", "workflows", b"workflows"]) -> None: ...

global___GetWorkflowsResponse = GetWorkflowsResponse

@typing_extensions.final
class CreateWorkflowRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    WORKFLOW_FIELD_NUMBER: builtins.int
    name: builtins.str
    @property
    def workflow(self) -> protos.playbooks.workflow_pb2.Workflow: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        workflow: protos.playbooks.workflow_pb2.Workflow | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["workflow", b"workflow"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "workflow", b"workflow"]) -> None: ...

global___CreateWorkflowRequest = CreateWorkflowRequest

@typing_extensions.final
class CreateWorkflowResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    WORKFLOW_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def message(self) -> protos.base_pb2.Message: ...
    @property
    def workflow(self) -> protos.playbooks.workflow_pb2.Workflow: ...
    def __init__(
        self,
        *,
        success: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        message: protos.base_pb2.Message | None = ...,
        workflow: protos.playbooks.workflow_pb2.Workflow | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success", "workflow", b"workflow"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "success", b"success", "workflow", b"workflow"]) -> None: ...

global___CreateWorkflowResponse = CreateWorkflowResponse
