"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.base_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class DatadogServiceAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Metric(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        METRIC_FAMILY_FIELD_NUMBER: builtins.int
        METRIC_FIELD_NUMBER: builtins.int
        @property
        def metric_family(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def metric(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            metric_family: google.protobuf.wrappers_pb2.StringValue | None = ...,
            metric: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["metric", b"metric", "metric_family", b"metric_family"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["metric", b"metric", "metric_family", b"metric_family"]) -> None: ...

    SERVICE_NAME_FIELD_NUMBER: builtins.int
    ENVIRONMENTS_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    @property
    def service_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def environments(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DatadogServiceAssetModel.Metric]: ...
    def __init__(
        self,
        *,
        service_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        environments: collections.abc.Iterable[builtins.str] | None = ...,
        metrics: collections.abc.Iterable[global___DatadogServiceAssetModel.Metric] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["service_name", b"service_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["environments", b"environments", "metrics", b"metrics", "service_name", b"service_name"]) -> None: ...

global___DatadogServiceAssetModel = DatadogServiceAssetModel

@typing_extensions.final
class DatadogServiceAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class DatadogServiceAssetOption(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        METRIC_FAMILIES_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def metric_families(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            metric_families: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["metric_families", b"metric_families", "name", b"name"]) -> None: ...

    SERVICES_FIELD_NUMBER: builtins.int
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DatadogServiceAssetOptions.DatadogServiceAssetOption]: ...
    def __init__(
        self,
        *,
        services: collections.abc.Iterable[global___DatadogServiceAssetOptions.DatadogServiceAssetOption] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["services", b"services"]) -> None: ...

global___DatadogServiceAssetOptions = DatadogServiceAssetOptions

@typing_extensions.final
class DatadogAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    DATADOG_SERVICE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    connector_type: protos.base_pb2.Source.ValueType
    type: protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def datadog_service(self) -> global___DatadogServiceAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: protos.base_pb2.Source.ValueType = ...,
        type: protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        datadog_service: global___DatadogServiceAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "datadog_service", b"datadog_service", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "connector_type", b"connector_type", "datadog_service", b"datadog_service", "id", b"id", "last_updated", b"last_updated", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["asset", b"asset"]) -> typing_extensions.Literal["datadog_service"] | None: ...

global___DatadogAssetModel = DatadogAssetModel

@typing_extensions.final
class DatadogAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DatadogAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___DatadogAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["assets", b"assets"]) -> None: ...

global___DatadogAssets = DatadogAssets
