# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/connectors/assets/gcm_asset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos import base_pb2 as protos_dot_base__pb2
from protos.connectors import connector_pb2 as protos_dot_connectors_dot_connector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(protos/connectors/assets/gcm_asset.proto\x12\x18protos.connectors.assets\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11protos/base.proto\x1a!protos/connectors/connector.proto\"\x84\x02\n\x13GcmMetricAssetModel\x12\x31\n\x0bmetric_type\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12Y\n\x16label_value_metric_map\x18\x02 \x03(\x0b\x32\x39.protos.connectors.assets.GcmMetricAssetModel.MetricLabel\x1a_\n\x0bMetricLabel\x12*\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x13\n\x0b\x64\x65scription\x18\x02 \x03(\t\x12\x0f\n\x07metrics\x18\x03 \x03(\t\"-\n\x15GcmMetricAssetOptions\x12\x14\n\x0cmetric_types\x18\x01 \x03(\t\"\xec\x01\n\rGcmAssetModel\x12(\n\x02id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12&\n\x0e\x63onnector_type\x18\x02 \x01(\x0e\x32\x0e.protos.Source\x12%\n\x04type\x18\x03 \x01(\x0e\x32\x17.protos.SourceModelType\x12\x14\n\x0clast_updated\x18\x04 \x01(\x10\x12\x43\n\ngcm_metric\x18\x06 \x01(\x0b\x32-.protos.connectors.assets.GcmMetricAssetModelH\x00\x42\x07\n\x05\x61sset\"D\n\tGcmAssets\x12\x37\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\'.protos.connectors.assets.GcmAssetModelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.connectors.assets.gcm_asset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCMMETRICASSETMODEL._serialized_start=157
  _GCMMETRICASSETMODEL._serialized_end=417
  _GCMMETRICASSETMODEL_METRICLABEL._serialized_start=322
  _GCMMETRICASSETMODEL_METRICLABEL._serialized_end=417
  _GCMMETRICASSETOPTIONS._serialized_start=419
  _GCMMETRICASSETOPTIONS._serialized_end=464
  _GCMASSETMODEL._serialized_start=467
  _GCMASSETMODEL._serialized_end=703
  _GCMASSETS._serialized_start=705
  _GCMASSETS._serialized_end=773
# @@protoc_insertion_point(module_scope)
