"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.connectors.connector_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PostgresDatabaseAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class PostgresTable(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class PostgresColumn(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            COLUMN_NAME_FIELD_NUMBER: builtins.int
            DATA_TYPE_FIELD_NUMBER: builtins.int
            @property
            def column_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
            @property
            def data_type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
            def __init__(
                self,
                *,
                column_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
                data_type: google.protobuf.wrappers_pb2.StringValue | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["column_name", b"column_name", "data_type", b"data_type"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["column_name", b"column_name", "data_type", b"data_type"]) -> None: ...

        NAME_FIELD_NUMBER: builtins.int
        TIMESTAMP_COLUMN_FIELD_NUMBER: builtins.int
        COLUMNS_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def timestamp_column(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def columns(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PostgresDatabaseAssetModel.PostgresTable.PostgresColumn]: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            timestamp_column: google.protobuf.wrappers_pb2.StringValue | None = ...,
            columns: collections.abc.Iterable[global___PostgresDatabaseAssetModel.PostgresTable.PostgresColumn] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name", "timestamp_column", b"timestamp_column"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["columns", b"columns", "name", b"name", "timestamp_column", b"timestamp_column"]) -> None: ...

    DATABASE_FIELD_NUMBER: builtins.int
    TABLES_FIELD_NUMBER: builtins.int
    @property
    def database(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def tables(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PostgresDatabaseAssetModel.PostgresTable]: ...
    def __init__(
        self,
        *,
        database: google.protobuf.wrappers_pb2.StringValue | None = ...,
        tables: collections.abc.Iterable[global___PostgresDatabaseAssetModel.PostgresTable] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["database", b"database"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["database", b"database", "tables", b"tables"]) -> None: ...

global___PostgresDatabaseAssetModel = PostgresDatabaseAssetModel

@typing_extensions.final
class PostgresDatabaseAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATABASES_FIELD_NUMBER: builtins.int
    @property
    def databases(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        databases: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["databases", b"databases"]) -> None: ...

global___PostgresDatabaseAssetOptions = PostgresDatabaseAssetOptions

@typing_extensions.final
class PostgresAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    POSTGRES_DATABASE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    connector_type: protos.connectors.connector_pb2.ConnectorType.ValueType
    type: protos.connectors.connector_pb2.ConnectorMetadataModelType.ValueType
    last_updated: builtins.int
    @property
    def postgres_database(self) -> global___PostgresDatabaseAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: protos.connectors.connector_pb2.ConnectorType.ValueType = ...,
        type: protos.connectors.connector_pb2.ConnectorMetadataModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        postgres_database: global___PostgresDatabaseAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "id", b"id", "postgres_database", b"postgres_database"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "postgres_database", b"postgres_database", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["asset", b"asset"]) -> typing_extensions.Literal["postgres_database"] | None: ...

global___PostgresAssetModel = PostgresAssetModel

@typing_extensions.final
class PostgresAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PostgresAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___PostgresAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["assets", b"assets"]) -> None: ...

global___PostgresAssets = PostgresAssets
