"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.base_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SlackChannelAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ChannelMetadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IS_AUTO_RCA_ENABLED_FIELD_NUMBER: builtins.int
        @property
        def is_auto_rca_enabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            is_auto_rca_enabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["is_auto_rca_enabled", b"is_auto_rca_enabled"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["is_auto_rca_enabled", b"is_auto_rca_enabled"]) -> None: ...

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    CHANNEL_NAME_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    @property
    def channel_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def channel_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def metadata(self) -> global___SlackChannelAssetModel.ChannelMetadata: ...
    def __init__(
        self,
        *,
        channel_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        channel_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        metadata: global___SlackChannelAssetModel.ChannelMetadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["channel_id", b"channel_id", "channel_name", b"channel_name", "metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_id", b"channel_id", "channel_name", b"channel_name", "metadata", b"metadata"]) -> None: ...

global___SlackChannelAssetModel = SlackChannelAssetModel

@typing_extensions.final
class SlackChannelAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_IDS_FIELD_NUMBER: builtins.int
    @property
    def channel_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        channel_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_ids", b"channel_ids"]) -> None: ...

global___SlackChannelAssetOptions = SlackChannelAssetOptions

@typing_extensions.final
class SlackAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    SLACK_CHANNEL_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    connector_type: protos.base_pb2.Source.ValueType
    type: protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def slack_channel(self) -> global___SlackChannelAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: protos.base_pb2.Source.ValueType = ...,
        type: protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        slack_channel: global___SlackChannelAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "id", b"id", "slack_channel", b"slack_channel"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "slack_channel", b"slack_channel", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["asset", b"asset"]) -> typing_extensions.Literal["slack_channel"] | None: ...

global___SlackAssetModel = SlackAssetModel

@typing_extensions.final
class SlackAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SlackAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___SlackAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["assets", b"assets"]) -> None: ...

global___SlackAssets = SlackAssets
