# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/workflow_actions/api_trigger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos import base_pb2 as protos_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3protos/playbooks/workflow_actions/api_trigger.proto\x12\x10protos.playbooks\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11protos/base.proto\"\xc9\x01\n\x18\x41piTriggerWorkflowAction\x12.\n\x08\x65ndpoint\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06method\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12(\n\x07headers\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12%\n\x04\x62ody\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Structb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.workflow_actions.api_trigger_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APITRIGGERWORKFLOWACTION._serialized_start=155
  _APITRIGGERWORKFLOWACTION._serialized_end=356
# @@protoc_insertion_point(module_scope)
