"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PagerdutyNotesWorkflowAction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PD_INCIDENT_ID_FIELD_NUMBER: builtins.int
    @property
    def pd_incident_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        pd_incident_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pd_incident_id", b"pd_incident_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pd_incident_id", b"pd_incident_id"]) -> None: ...

global___PagerdutyNotesWorkflowAction = PagerdutyNotesWorkflowAction
