"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.wrappers_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PlaybookExecute(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYBOOK_ID_FIELD_NUMBER: builtins.int
    GLOBAL_VARIABLE_SET_FIELD_NUMBER: builtins.int
    @property
    def playbook_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def global_variable_set(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        playbook_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        global_variable_set: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["global_variable_set", b"global_variable_set", "playbook_id", b"playbook_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["global_variable_set", b"global_variable_set", "playbook_id", b"playbook_id"]) -> None: ...

global___PlaybookExecute = PlaybookExecute
