# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/workflow_actions/smtp_email.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos import base_pb2 as protos_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2protos/playbooks/workflow_actions/smtp_email.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11protos/base.proto\"\xa4\x01\n\x17SMTPEmailWorkflowAction\x12.\n\x08to_email\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07subject\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12*\n\x04\x62ody\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValueb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.workflow_actions.smtp_email_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SMTPEMAILWORKFLOWACTION._serialized_start=124
  _SMTPEMAILWORKFLOWACTION._serialized_end=288
# @@protoc_insertion_point(module_scope)
