export const Key = {
  METHOD: "method",
  URL: "url",
  HEADERS: "headers",
  PAYLOAD: "payload",
  TIMEOUT: "timeout",
  NAMESPACE: "namespace",
  REGION: "region",
  DIMENSION_NAME: "dimensions.0.name",
  DIMENSION_VALUE: "dimensions.0.value",
  METRIC_NAME: "metric_name",
  WORKSPACE_ID: "workspace_id",
  FILTER_QUERY: "filter_query",
  TIMESPAN: "timespan",
  COMMAND: "command",
  REMOTE_SERVER: "remote_server",
  DATABASE: "database",
  QUERY: "query",
  LOG_GROUP_NAME: "log_group_name",
  SERVICE_NAME: "service_name",
  ENVIRONMENT_NAME: "environment_name",
  METRIC_FAMILY: "metric_family",
  METRIC: "metric",
  PROCESS_FUNCTION: "process_function",
  QUERY1: "queries.0",
  QUERY2: "queries.1",
  FORMULA: "formula",
  CLUSTER: "cluster",
  INDEX: "index",
  LUCENE_QUERY: "lucene_query",
  LIMIT: "limit",
  OFFSET: "offset",
  SORT_DESC: "sort_desc",
  TIMESTAMP_FIELD: "timestamp_field",
  ZONE: "zone",
} as const;

export type KeyType = (typeof Key)[keyof typeof Key];
