export enum ExecutionStatus {
  CREATED = "CREATED",
  RUNNING = "RUNNING",
  FINISHED = "FINISHED",
  FAILED = "FAILED",
  SCHEDULED = "SCHEDULED",
  WORKFLOW_CREATED = "WORKFLOW_CREATED",
  WORKFLOW_RUNNING = "WORKFLOW_RUNNING",
  WORKFLOW_FINISHED = "WORKFLOW_FINISHED",
  WORKFLOW_FAILED = "WORKFLOW_FAILED",
  WORKFLOW_SCHEDULED = "WORKFLOW_SCHEDULED",
}
