export enum TaskType {
  Documentation = "documentation",
  Cloudwatch = "cloudwatch",
  Grafana = "grafana",
  NewRelic = "new_relic",
  Datadog = "datadog",
  Clickhouse = "clickhouse",
  Postgres = "postgres",
  Eks = "eks",
  SqlDatabaseConnection = "sql_database_connection",
  Api = "api",
  Bash = "bash",
  GrafanaMimir = "grafana_mimir",
  Azure = "azure",
  Gke = "gke",
  ElasticSearch = "elastic_search",
  Slack = "SEND_MESSAGE",
}
