# Generated by Django 4.1.4 on 2024-04-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowexecution_workflowexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='total_executions',
            field=models.IntegerField(default=0),
        ),
    ]
