# Generated by Django 4.1.4 on 2024-04-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
        ('workflows', '0003_workflowexecution_total_executions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowexecution',
            unique_together={('account', 'workflow_run_id', 'scheduled_at')},
        ),
    ]
