# Generated by Django 4.1.4 on 2024-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_workflowexecution_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecution',
            name='interval',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
