# Generated by Django 4.1.13 on 2024-06-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflowexecution_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecution',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='workflowexecution',
            name='total_executions',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='schedule_type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'ONE_OFF'), (2, 'INTERVAL'), (3, 'CRON')], db_index=True),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'API'), (2, 'SLACK_MESSAGE'), (3, 'SLACK_THREAD_REPLY')], db_index=True),
        ),
        migrations.AlterField(
            model_name='workflowentrypoint',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'API'), (2, 'SLACK_CHANNEL_ALERT')], db_index=True),
        ),
    ]
