# Generated by Django 4.1.13 on 2024-06-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_workflow_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowentrypoint',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'API'), (2, 'SLACK_CHANNEL_ALERT'), (3, 'PAGERDUTY_INCIDENT')], db_index=True),
        ),
    ]
