# Generated by Django 4.1.13 on 2024-07-11 06:32

from django.db import migrations


def remove_all_existing_execution_metadata(apps, schema_editor):
    WorkflowExecution = apps.get_model("workflows", "WorkflowExecution")

    for we in WorkflowExecution.objects.all():
        try:
            we.metadata = None
            we.save()
        except Exception as e:
            print(f"Failed to update workflow execution {we.id} with error: {str(e)}")


class Migration(migrations.Migration):
    dependencies = [
        ('workflows', '0011_alter_workflowaction_type_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_all_existing_execution_metadata, migrations.RunPython.noop)
    ]
