# Generated by Django 4.1.13 on 2024-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_alter_workflowaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'STANDARD'), (2, 'DYNAMIC_ALERT')], db_index=True, default=1),
            preserve_default=False,
        ),
    ]
