# Generated by Django 4.1.13 on 2024-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_workflow_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowexecution',
            old_name='workflow_execution_configuration',
            new_name='execution_configuration',
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='keep_alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='latest_scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='total_executions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowexecutionlog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
