# Generated by Django 4.1.13 on 2024-08-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0015_rename_workflow_execution_configuration_workflowexecution_execution_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowexecutionlog',
            name='scheduled_at',
        ),
    ]
