# Generated by Django 4.1.13 on 2024-08-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_remove_workflowexecutionlog_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowentrypoint',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'API'), (2, 'SLACK_CHANNEL_ALERT'), (3, 'PAGERDUTY_INCIDENT'), (4, 'ZENDUTY_INCIDENT')], db_index=True),
        ),
    ]