# Generated by Django 4.1.13 on 2024-08-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_alter_workflowentrypoint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'API'), (2, 'SLACK_MESSAGE'), (3, 'SLACK_THREAD_REPLY'), (4, 'MS_TEAMS_MESSAGE_WEBHOOK'), (5, 'PAGERDUTY_NOTES'), (6, 'SMTP_EMAIL'), (7, 'ZENDUTY_NOTES')], db_index=True),
        ),
    ]
