"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class BigQuery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TaskType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TaskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BigQuery._TaskType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: BigQuery._TaskType.ValueType  # 0
        QUERY_TABLE: BigQuery._TaskType.ValueType  # 1

    class TaskType(_TaskType, metaclass=_TaskTypeEnumTypeWrapper): ...
    UNKNOWN: BigQuery.TaskType.ValueType  # 0
    QUERY_TABLE: BigQuery.TaskType.ValueType  # 1

    @typing_extensions.final
    class QueryTable(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DATASET_FIELD_NUMBER: builtins.int
        TABLE_FIELD_NUMBER: builtins.int
        QUERY_FIELD_NUMBER: builtins.int
        LIMIT_FIELD_NUMBER: builtins.int
        @property
        def dataset(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def table(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def query(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def limit(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        def __init__(
            self,
            *,
            dataset: google.protobuf.wrappers_pb2.StringValue | None = ...,
            table: google.protobuf.wrappers_pb2.StringValue | None = ...,
            query: google.protobuf.wrappers_pb2.StringValue | None = ...,
            limit: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["dataset", b"dataset", "limit", b"limit", "query", b"query", "table", b"table"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["dataset", b"dataset", "limit", b"limit", "query", b"query", "table", b"table"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    QUERY_TABLE_FIELD_NUMBER: builtins.int
    type: global___BigQuery.TaskType.ValueType
    @property
    def query_table(self) -> global___BigQuery.QueryTable: ...
    def __init__(
        self,
        *,
        type: global___BigQuery.TaskType.ValueType = ...,
        query_table: global___BigQuery.QueryTable | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["query_table", b"query_table", "task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["query_table", b"query_table", "task", b"task", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task", b"task"]) -> typing_extensions.Literal["query_table"] | None: ...

global___BigQuery = BigQuery
