"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PlaybookEksDataFetchTask(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _CommandType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _CommandTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PlaybookEksDataFetchTask._CommandType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: PlaybookEksDataFetchTask._CommandType.ValueType  # 0
        GET_PODS: PlaybookEksDataFetchTask._CommandType.ValueType  # 1
        GET_DEPLOYMENTS: PlaybookEksDataFetchTask._CommandType.ValueType  # 2
        GET_EVENTS: PlaybookEksDataFetchTask._CommandType.ValueType  # 3
        GET_SERVICES: PlaybookEksDataFetchTask._CommandType.ValueType  # 4

    class CommandType(_CommandType, metaclass=_CommandTypeEnumTypeWrapper): ...
    UNKNOWN: PlaybookEksDataFetchTask.CommandType.ValueType  # 0
    GET_PODS: PlaybookEksDataFetchTask.CommandType.ValueType  # 1
    GET_DEPLOYMENTS: PlaybookEksDataFetchTask.CommandType.ValueType  # 2
    GET_EVENTS: PlaybookEksDataFetchTask.CommandType.ValueType  # 3
    GET_SERVICES: PlaybookEksDataFetchTask.CommandType.ValueType  # 4

    COMMAND_TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    REGION_FIELD_NUMBER: builtins.int
    CLUSTER_FIELD_NUMBER: builtins.int
    NAMESPACE_FIELD_NUMBER: builtins.int
    command_type: global___PlaybookEksDataFetchTask.CommandType.ValueType
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def region(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def cluster(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def namespace(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        command_type: global___PlaybookEksDataFetchTask.CommandType.ValueType = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        region: google.protobuf.wrappers_pb2.StringValue | None = ...,
        cluster: google.protobuf.wrappers_pb2.StringValue | None = ...,
        namespace: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cluster", b"cluster", "description", b"description", "namespace", b"namespace", "region", b"region"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cluster", b"cluster", "command_type", b"command_type", "description", b"description", "namespace", b"namespace", "region", b"region"]) -> None: ...

global___PlaybookEksDataFetchTask = PlaybookEksDataFetchTask
