# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/eks_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import base_pb2 as protos_dot_base__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7protos/playbooks/source_task_definitions/eks_task.proto\x12\x10protos.playbooks\x1a\x11protos/base.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8a\x03\n\x18PlaybookEksDataFetchTask\x12L\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x36.protos.playbooks.PlaybookEksDataFetchTask.CommandType\x12\x31\n\x0b\x64\x65scription\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06region\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07\x63luster\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\tnamespace\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"_\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08GET_PODS\x10\x01\x12\x13\n\x0fGET_DEPLOYMENTS\x10\x02\x12\x0e\n\nGET_EVENTS\x10\x03\x12\x10\n\x0cGET_SERVICES\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.eks_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYBOOKEKSDATAFETCHTASK._serialized_start=129
  _PLAYBOOKEKSDATAFETCHTASK._serialized_end=523
  _PLAYBOOKEKSDATAFETCHTASK_COMMANDTYPE._serialized_start=428
  _PLAYBOOKEKSDATAFETCHTASK_COMMANDTYPE._serialized_end=523
# @@protoc_insertion_point(module_scope)
