# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/gcm_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7protos/playbooks/source_task_definitions/gcm_task.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x04\n\x03Gcm\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.protos.playbooks.Gcm.TaskType\x12;\n\rmql_execution\x18\x02 \x01(\x0b\x32\".protos.playbooks.Gcm.MqlExecutionH\x00\x12\x42\n\x11\x66ilter_log_events\x18\x03 \x01(\x0b\x32%.protos.playbooks.Gcm.FilterLogEventsH\x00\x1aW\n\x0cMqlExecution\x12+\n\x05query\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x1a\n\x12timeseries_offsets\x18\x02 \x03(\r\x1a\x8e\x02\n\x0f\x46ilterLogEvents\x12\x32\n\x0c\x66ilter_query\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x34\n\x0eresource_names\x18\x02 \x03(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08order_by\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\tpage_size\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12\x30\n\npage_token\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"A\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rMQL_EXECUTION\x10\x01\x12\x15\n\x11\x46ILTER_LOG_EVENTS\x10\x02\x42\x06\n\x04taskb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.gcm_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GCM._serialized_start=143
  _GCM._serialized_end=760
  _GCM_MQLEXECUTION._serialized_start=325
  _GCM_MQLEXECUTION._serialized_end=412
  _GCM_FILTERLOGEVENTS._serialized_start=415
  _GCM_FILTERLOGEVENTS._serialized_end=685
  _GCM_TASKTYPE._serialized_start=687
  _GCM_TASKTYPE._serialized_end=752
# @@protoc_insertion_point(module_scope)
