# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/grafana_loki_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos.playbooks.source_task_definitions import promql_task_pb2 as protos_dot_playbooks_dot_source__task__definitions_dot_promql__task__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@protos/playbooks/source_task_definitions/grafana_loki_task.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\x1a:protos/playbooks/source_task_definitions/promql_task.proto\"\xfd\x02\n\x0bGrafanaLoki\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.protos.playbooks.GrafanaLoki.TaskType\x12=\n\nquery_logs\x18\x65 \x01(\x0b\x32\'.protos.playbooks.GrafanaLoki.QueryLogsH\x00\x1a\xc7\x01\n\tQueryLogs\x12+\n\x05query\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nstart_time\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12.\n\x08\x65nd_time\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12+\n\x05limit\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\"\'\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nQUERY_LOGS\x10\x01\x42\x06\n\x04taskb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.grafana_loki_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRAFANALOKI._serialized_start=179
  _GRAFANALOKI._serialized_end=560
  _GRAFANALOKI_QUERYLOGS._serialized_start=312
  _GRAFANALOKI_QUERYLOGS._serialized_end=511
  _GRAFANALOKI_TASKTYPE._serialized_start=513
  _GRAFANALOKI_TASKTYPE._serialized_end=552
# @@protoc_insertion_point(module_scope)
