# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/rootly_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:protos/playbooks/source_task_definitions/rootly_task.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb5\x02\n\x06Rootly\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.protos.playbooks.Rootly.TaskType\x12I\n\x13send_timeline_event\x18\x02 \x01(\x0b\x32*.protos.playbooks.Rootly.SendTimelineEventH\x00\x1au\n\x11SendTimelineEvent\x12\x31\n\x0bincident_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"0\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x17\n\x13SEND_TIMELINE_EVENT\x10\x01\x42\x06\n\x04taskb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.rootly_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOTLY._serialized_start=143
  _ROOTLY._serialized_end=452
  _ROOTLY_SENDTIMELINEEVENT._serialized_start=277
  _ROOTLY_SENDTIMELINEEVENT._serialized_end=394
  _ROOTLY_TASKTYPE._serialized_start=396
  _ROOTLY_TASKTYPE._serialized_end=444
# @@protoc_insertion_point(module_scope)
