# Generated by Django 4.1.13 on 2024-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_image_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.TextField(blank=True, default="Untitled", null=True),
        ),
    ]
