apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-central
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match **>
      @type stdout
    </match>