apiVersion: v1
kind: Pod
metadata:
  name: central-log-pod
  labels:
    app: central-log
spec:
  containers:
    - name: log-receiver
      image: fluent/fluentd:v1.12-debian-1
      volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
      ports:
        - containerPort: 24224
      args:
        - "fluentd"
        - "-c"
        - "/fluentd/etc/fluent.conf"
  volumes:
    - name: config-volume
      configMap:
        name: fluentd-config-central
      