"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.base_pb2
import protos.literal_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SortOrder:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SortOrderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SortOrder.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ASC: _SortOrder.ValueType  # 0
    DESC: _SortOrder.ValueType  # 1

class SortOrder(_SortOrder, metaclass=_SortOrderEnumTypeWrapper): ...

ASC: SortOrder.ValueType  # 0
DESC: SortOrder.ValueType  # 1
global___SortOrder = SortOrder

@typing_extensions.final
class OpRhs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OP_FIELD_NUMBER: builtins.int
    RHS_FIELD_NUMBER: builtins.int
    op: protos.base_pb2.Op.ValueType
    rhs: protos.literal_pb2.LiteralType.ValueType
    def __init__(
        self,
        *,
        op: protos.base_pb2.Op.ValueType = ...,
        rhs: protos.literal_pb2.LiteralType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["op", b"op", "rhs", b"rhs"]) -> None: ...

global___OpRhs = OpRhs

@typing_extensions.final
class OpMapping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LHS_FIELD_NUMBER: builtins.int
    OP_RHS_FIELD_NUMBER: builtins.int
    lhs: protos.literal_pb2.LiteralType.ValueType
    @property
    def op_rhs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OpRhs]: ...
    def __init__(
        self,
        *,
        lhs: protos.literal_pb2.LiteralType.ValueType = ...,
        op_rhs: collections.abc.Iterable[global___OpRhs] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["lhs", b"lhs", "op_rhs", b"op_rhs"]) -> None: ...

global___OpMapping = OpMapping

@typing_extensions.final
class ColumnIdentifier(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    type: protos.literal_pb2.LiteralType.ValueType
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        type: protos.literal_pb2.LiteralType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "type", b"type"]) -> None: ...

global___ColumnIdentifier = ColumnIdentifier

@typing_extensions.final
class Expression(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLUMN_IDENTIFIER_FIELD_NUMBER: builtins.int
    LITERAL_FIELD_NUMBER: builtins.int
    @property
    def column_identifier(self) -> global___ColumnIdentifier: ...
    @property
    def literal(self) -> protos.literal_pb2.Literal: ...
    def __init__(
        self,
        *,
        column_identifier: global___ColumnIdentifier | None = ...,
        literal: protos.literal_pb2.Literal | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["column_identifier", b"column_identifier", "literal", b"literal", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["column_identifier", b"column_identifier", "literal", b"literal", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["column_identifier", "literal"] | None: ...

global___Expression = Expression

@typing_extensions.final
class Filter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LHS_FIELD_NUMBER: builtins.int
    OP_FIELD_NUMBER: builtins.int
    RHS_FIELD_NUMBER: builtins.int
    FILTERS_FIELD_NUMBER: builtins.int
    @property
    def lhs(self) -> global___Expression: ...
    op: protos.base_pb2.Op.ValueType
    @property
    def rhs(self) -> global___Expression: ...
    @property
    def filters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Filter]: ...
    def __init__(
        self,
        *,
        lhs: global___Expression | None = ...,
        op: protos.base_pb2.Op.ValueType = ...,
        rhs: global___Expression | None = ...,
        filters: collections.abc.Iterable[global___Filter] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["lhs", b"lhs", "rhs", b"rhs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["filters", b"filters", "lhs", b"lhs", "op", b"op", "rhs", b"rhs"]) -> None: ...

global___Filter = Filter

@typing_extensions.final
class QueryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILTER_FIELD_NUMBER: builtins.int
    SELECTION_FIELD_NUMBER: builtins.int
    DISTINCT_SELECTIONS_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    @property
    def filter(self) -> global___Filter: ...
    @property
    def selection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Expression]: ...
    distinct_selections: builtins.bool
    @property
    def order_by(self) -> global___OrderByExpression: ...
    def __init__(
        self,
        *,
        filter: global___Filter | None = ...,
        selection: collections.abc.Iterable[global___Expression] | None = ...,
        distinct_selections: builtins.bool = ...,
        order_by: global___OrderByExpression | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["filter", b"filter", "order_by", b"order_by"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["distinct_selections", b"distinct_selections", "filter", b"filter", "order_by", b"order_by", "selection", b"selection"]) -> None: ...

global___QueryRequest = QueryRequest

@typing_extensions.final
class OrderByExpression(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPRESSION_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    ALLOW_NULLS_FIELD_NUMBER: builtins.int
    NULLS_LAST_FIELD_NUMBER: builtins.int
    @property
    def expression(self) -> global___Expression: ...
    order: global___SortOrder.ValueType
    @property
    def allow_nulls(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def nulls_last(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        expression: global___Expression | None = ...,
        order: global___SortOrder.ValueType = ...,
        allow_nulls: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        nulls_last: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["allow_nulls", b"allow_nulls", "expression", b"expression", "nulls_last", b"nulls_last"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["allow_nulls", b"allow_nulls", "expression", b"expression", "nulls_last", b"nulls_last", "order", b"order"]) -> None: ...

global___OrderByExpression = OrderByExpression
