name: Deploy Coruscant

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  ssh-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SID_EC2_PEM_FILE }}

    - name: SSH and run script
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SID_EC2_PEM_FILE }} ec2-user@<CORUSCANT_EC2_IP_ADDRESS> 'bash -s' < /home/ec2-user/deploy.sh
